[package]
name = "iconer"
version = "0.2.2"
edition = "2021"
authors = ["Artur Gwo≈∫dziowski"]
keywords = ["icon converter"]
repository = "https://github.com/Arti-Code/iconer.git"

[dependencies]
ico = "0.3.0"


[build-dependencies]
embed-resource = "2.4.2"