[package]
name = "iconer"
version = "0.3.0"
edition = "2021"
authors = ["Artur Gwo≈∫dziowski"]
keywords = ["icon converter"]
repository = "https://github.com/Arti-Code/iconer.git"

[dependencies]
ico = "0.5.0"


[build-dependencies]
embed-resource = "3.0.6"